//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Factura
    {
        public int TN_IdFactura { get; set; }
        public int TN_IdVehiculo { get; set; }
        public int TN_IdUsuario { get; set; }
        public Nullable<int> TN_IdMarca { get; set; }
        public Nullable<int> TN_IdModelo { get; set; }
        public Nullable<int> TN_IdCapacidad { get; set; }
        public Nullable<int> TN_IdColor { get; set; }
        public Nullable<int> TN_IdAnno { get; set; }
        public Nullable<int> TN_IdMotor { get; set; }
        public Nullable<int> TN_IdDisenno { get; set; }
        public int TN_IdCompra { get; set; }
    
        public virtual TBL_Anno TBL_Anno { get; set; }
        public virtual TBL_Capacidad TBL_Capacidad { get; set; }
        public virtual TBL_Color TBL_Color { get; set; }
        public virtual TBL_Compra TBL_Compra { get; set; }
        public virtual TBL_Disenno TBL_Disenno { get; set; }
        public virtual TBL_Marca TBL_Marca { get; set; }
        public virtual TBL_Modelo TBL_Modelo { get; set; }
        public virtual TBL_Motor TBL_Motor { get; set; }
        public virtual TBL_Usuario TBL_Usuario { get; set; }
        public virtual TBL_Vehiculo TBL_Vehiculo { get; set; }
    }
}
