//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ventas_Vehiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Usuario()
        {
            this.TBL_Compra = new HashSet<TBL_Compra>();
            this.TBL_Compra1 = new HashSet<TBL_Compra>();
            this.TBL_Factura = new HashSet<TBL_Factura>();
        }
    
        public int TN_IdUsuario { get; set; }
        public string TC_TipoUsuario { get; set; }
        public int TN_Cedula { get; set; }
        public string TC_Nombre { get; set; }
        public string TC_PrimerApellido { get; set; }
        public string TC_SegundoApellido { get; set; }
        public string TC_Correo { get; set; }
        public string TC_Direccion { get; set; }
        public string TC_Clave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Compra> TBL_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Compra> TBL_Compra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Factura> TBL_Factura { get; set; }
    }
}
